services:
  app:
    platform: linux/x86_64
    container_name: redcap_docker-app-1
    build: app
    ports:
      - '8080:80'
    environment:
      PHP_EXTENSION_IMAGICK: 1
      TEMPLATE_PHP_INI: production
    depends_on:
      - db
    volumes:
      - ../tmp/:/var/www/html/temp:Z
      - ../edocs/:/var/www/html/edocs:Z
      # If you need to make on the fly modifications to the redcap_source dir, uncommenting the following may be helpful.
      # However, there will be a significant performance hit (especially on Windows).
      # Hacking run.sh to copy redcap_source to the container on every run may be faster for you.
      # - ../redcap_source/:/var/www/html/

  db:
    container_name: redcap_docker-db-1
    image: mysql:8.1
    ports:
      - '3400:3306'
    env_file:
      - env/db.env
    restart: always
    tmpfs: /var/lib/mysql

  mailhog:
    container_name: redcap_docker-mailhog-1
    image: mailhog/mailhog:v1.0.0
    ports:
      - "1025:1025"
      - "8025:8025"

  sftp:
    container_name: redcap_docker-sftp-1
    image: atmoz/sftp
    volumes:
      - ../redcap_cypress/cypress/sftp_uploads:/home/sftp-user/upload
    command: sftp-user:sftp-password

  azurite:
    # We spoof this domain because REDCap requires azure URLs to end in blob.core.windows.net
    container_name: devstoreaccount1.blob.core.windows.net
    image: mcr.microsoft.com/azure-storage/azurite
    volumes:
      - ./certs:/certs
    depends_on:
      - app
    command: |
      sh -c "
        sleep 10 && wget -O - redcap_docker-app-1/create-azure-container.php &
        azurite --inMemoryPersistence --blobHost 0.0.0.0 --blobPort 443 --cert /certs/devstoreaccount1.blob.core.windows.net.crt --key /certs/devstoreaccount1.blob.core.windows.net.key
      "
  
  webdav:
    container_name: redcap_docker-webdav-1
    image: bytemark/webdav
    volumes:
      - ../redcap_cypress/cypress/webdav_uploads:/var/lib/dav
    environment:
      AUTH_TYPE: Basic
      USERNAME: webdav-user
      PASSWORD: webdav-pass

  fake-gcs-server:
    container_name: redcap_docker-fake-gcs-server-1
    image: fsouza/fake-gcs-server
    volumes:
      - ../redcap_cypress/cypress/gcs_uploads:/data

  minio:
    container_name: redcap_docker-minio-1
    image: minio/minio
    volumes:
      - ../redcap_cypress/cypress/s3_uploads:/data
    command: server /data --console-address ":9001"
